Altered find() functions for python3 compatibility
Changed the char *name='' entries in the four find() definitions
containing them to be simple name=''.
This fixed the following error:
    TypeError: expected bytes, str found

(cherry picked from commit 8f2465435fdb54bbe12586a1158cb3c51ad45622)